### ISSUE TITLE
GROUP: Guidelines for participating in package reviews

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/EuroBioc2019#11]

**Comment by lwaldron** [comment]
A potential outcome:
 - [ ] A GitHub Action for the submission repo to allow potential reviewers to “follow” package submissions containing certain keywords, BiocViews, or Depends/Imports.

**Comment by lgatto** [comment]
I have closed the issue given that it didn't seem to be a good fit for this devel day, but I think this would really be a useful feature.
